const xisjusty = [
    "A cough is just a crunchy breath",
    "Showers are just domesticated waterfalls",
    "Beanbags are just boneless chairs",
    "Flour is just boneless bread",
    "Water is just boneless ice",
    "Mouthwash is just boneless toothpaste",
    "Octopus is just boneless spider",
    "Protective goggles are just eye condoms",
    "Sand is just boneless rocks",
    "Meatballs are just boneless steaks",
    "Bath is just domesticated lake",
    "Cotton is just boneless Q - tips",
    "Moonlight is just boneless sunlight",
    "Dust is just boneless Avengers",
    "Math is just boneless physics",
    "Curtains are just boneless walls",
    "Gas is just boneless dinosaurs",
    "Death is just boneless life",
    "Socks are just boneless shoes",
    "Mars is just boneless Snickers",
    "Software is just boneless hardware",
    "Paintball is just boneless American school",
    "Electricity is just domesticated lightning",
    "Bricks are just domesticated rocks",
    "AC is just domesticated wind",
    "Wi - Fi is just boneless internet",
    "Antifa is just domesticated terrorism",
    "Knives are just domesticated swords",
    "Vape is just a domesticated cloud",
    "Garden is just a domesticated forest",
    "Sleep is just domesticated death",
    "Lightbulb is just a domesticated star",
    "Cheese is just crunchy milk",
    "Juice is just boneless fruits",
    "C4 is just angry Playdoh",
    "Engine Oil is just Carbeque Sauce",
    "Cars are just Liberated Trains",
    "Bottled water is just enslaved moisture",
    "Radiation is just spicy air",
    "Brightness is just Visual Volume",
    "Vicks VapoRub is just spicy vaseline",
];

module.exports = async (msg) => {
    const i = Math.floor(Math.random() * xisjusty.length);
    const reply = xisjusty[i];
    await msg.channel.send(`${msg.author} ${reply} 🚂`);
};
